name: <Name of the job>

# Controls when the workflow will run
on:
  # Triggers the workflow on PRs
  # pull_request:
  #   branches:
  #     - main

  # Triggers the workflow 3 am every Saturday
  schedule:
    - cron: "0 3 * * 6"
    
jobs:
  build:
    name: Build and publish new release
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Ensure code is checked out

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version of setup-python
        with:
          python-version: "3.10.16"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: List files in the repository (recursive)
        run: |
          ls -alR  # Lists all files to check the directory structure

      - name: Run app
        run: |
          python <path>.py 




      # - name: Check that versions match
      #   id: version
      #   run: |
      #     echo "Release tag: [${{ github.event.release.tag_name }}]"
      #     PACKAGE_VERSION=$(python -c "import ccds; print(ccds.__version__)")
      #     echo "Package version: [$PACKAGE_VERSION]"
      #     [ ${{ github.event.release.tag_name }} == "v$PACKAGE_VERSION" ] || { exit 1; }
      #     echo "::set-output name=major_minor_version::v${PACKAGE_VERSION%.*}"

      # - name: Build package
      #   run: |
      #     make dist
          
      # - name: Publish to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.3.0
      #   with:
      #     user: ${{ secrets.PYPI_TEST_USERNAME }}
      #     password: ${{ secrets.PYPI_TEST_PASSWORD }}
      #     repository_url: https://test.pypi.org/legacy/
      #     skip_existing: true

      # - name: Publish to Production PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.3.0
      #   with:
      #     user: ${{ secrets.PYPI_PROD_USERNAME }}
      #     password: ${{ secrets.PYPI_PROD_PASSWORD }}
      #     skip_existing: false